### ISSUE TITLE
A few issues with my project source code

### ISSUE THREAD

**Issue by ErikReider** [matbme/tree-sitter-vala#3] opened 2022-02-07 17:52 UTC
Found a few bugs through my [projects](https://github.com/ErikReider/SwayNotificationCenter) source code. Too many bugs to create separate issues (sorry :/ )...

I'm using the [vscode](https://github.com/Mofiqul/vscode.nvim) colorscheme in NeoVim

Here are a few bullets and screenshots:

- C-style comments not ending correctly? [Lines](https://github.com/ErikReider/SwayNotificationCenter/blob/90768ce824a9c621f6fd7c7ffd4eb9f21e001d07/src/configModel/configModel.vala#L147-L162)
![image](https://user-images.githubusercontent.com/35975961/152841441-9bdbae80-3013-4f88-9ed7-6490692a6aca.png)
- Preprocessor (#if, #endif) make the ConfigModel class light blue (pic above). [Lines](https://github.com/ErikReider/SwayNotificationCenter/blob/90768ce824a9c621f6fd7c7ffd4eb9f21e001d07/src/configModel/configModel.vala#L41-L147)

- Appending strings to `string[]` sometimes works and gets worse if I comment those lines out. [Lines](https://github.com/ErikReider/SwayNotificationCenter/blob/90768ce824a9c621f6fd7c7ffd4eb9f21e001d07/src/configModel/configModel.vala#L41-L68)
![image](https://user-images.githubusercontent.com/35975961/152845100-d1dc1245-dd26-46b9-9a09-2ed9f7b3eda0.png)
![image](https://user-images.githubusercontent.com/35975961/152845166-06b0b9ba-e61e-4486-a788-adf13210da33.png)

- Multi line strings become green? [Lines](https://github.com/ErikReider/SwayNotificationCenter/blob/90768ce824a9c621f6fd7c7ffd4eb9f21e001d07/src/notification/notification.vala#L143-L145)
![image](https://user-images.githubusercontent.com/35975961/152842397-ca4953c9-b0b6-4b47-9824-3aad5d6d60f9.png)

- Also seen in the screenshots above is that some variables are highlighted as if they're classes

Edit: I just realized that all of the screenshots were taken with [vala.vim](https://github.com/arrufat/vala.vim) installed. I'll update the screenshots

Edit 2: Updated screenshots

Edit 3: Added perma links to code lines

**Comment by matbme** [comment] 2022-02-07 23:13
Hi, thanks for the feedback! 

Just pushed a commit which fixes some issues I had while using the parser. C-style comments were one of them and should now be working.  

I believe the other bugs are caused by the fact I ~forgot~ did not yet implement Preprocessor expressions, will do it tomorrow.

**Comment by ErikReider** [comment] 2022-02-07 23:14
Awesome! I'll try it tomorrow :)

**Comment by ErikReider** [comment] 2022-02-07 23:51
Is there an easy way of updating? TSUpdate says that everything is up to date

**Comment by matbme** [comment] 2022-02-08 00:25
IIRC nvim-treesitter has an [automated script](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/.github/workflows/update-parsers-pr.yml) that periodically searches for new commits inside language implementations and test them. We just have to wait for it to run again.

You should see a commit named `Update lockfile.json` in the next hour or so. 


Edit: It actually runs once a day unless there is a new commit to master. If you want to test it now, you can [manually add](https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers) the parser

**Comment by ErikReider** [comment] 2022-02-08 14:35
The comments work now! :)

Still a few issues though:
- Variables are green
- The multi-line strings are now green (seems to kinda be working due to the escaped quotation-mark)
![image](https://user-images.githubusercontent.com/35975961/153005693-a4b460d6-0854-43c9-b2c2-cc273968af49.png)

- Some data types are colored as if they are classes:
VSCode:
![image](https://user-images.githubusercontent.com/35975961/153007342-27b57c8c-af9d-4118-84fa-5924771e4b43.png)
NeoVim:
![image](https://user-images.githubusercontent.com/35975961/153007445-d7ce7609-508a-4f87-8349-be90a5202fc3.png)
 
- After removing one of the enums, everything white starts to look normal
![image](https://user-images.githubusercontent.com/35975961/153008103-807fd3ce-9ca3-41e5-96d6-f9c19890b0c1.png)
![image](https://user-images.githubusercontent.com/35975961/153008898-096df0b4-fcaf-4925-a291-7c384da56461.png)

Thanks for your hard work! :)

**Comment by matbme** [comment] 2022-02-09 01:03
Added preprocessor and structs with functions should now work. I'll still give a more in-depth look into coloring in the future and create a MR to nvim-treesitter

**Comment by ErikReider** [comment] 2022-02-09 14:41
Awesome! Thanks! The only things left (that I've found) is the variable and data type coloring :)

**Comment by matbme** [comment] 2022-02-11 17:34
Coloring improvements have been [merged](https://github.com/nvim-treesitter/nvim-treesitter/pull/2513) in nvim-treesitter.

**Closed as completed** 2022-02-11 17:35 UTC
